config/routes.rb
Rails.application.routes.draw do
  get :signin,        to: "sessions#new"
  get :signup,        to: "users#new"
  delete :signout,    to: "sessions#destroy"

  resources :users, only: :create
  namespace :users do
    get :search, to: "search#index", as: :search, defaults: { format: 'json' }
  end

  resources :sessions, only: :create
  resources :tiles, only: :create
  resources :meeples, only: :create

  resources :games, only: [:new, :create, :show, :index] do
    scope module: :games do
      resource :board, only: :show
      resources :rounds, only: :create
    end
  end

  root "home#index"

  mount ActionCable.server => "/cable"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || "TCarc" %></title>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand">Carcassonne</a>
      </div>
      <ul class="nav navbar-nav">
        <li class='<%= 'active' if current_page?(root_path) %>'><a href="#">Home</a></li>
        <li class='<%= 'active' if current_page?(games_path) %>'>
          <%= link_to "Games", games_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li>
            <%= link_to "account-path" do %>
              <span class="glyphicon glyphicon-user"><%= current_user.username %></span>
            <% end %>
          </li>
          <li>
            <%= link_to signout_path, method: :delete do %>
              Sign Out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to signin_path do %>
              Sign In
            <% end %>
          </li>
          <li>
            <%= link_to signup_path do %>
              Sign Up
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>

</body>
</html>